export type PortfolioCategory = 
  | 'all'
  | 'manicures'
  | 'pedicures'
  | 'nail-art'
  | 'special-occasions'
  | 'seasonal-designs'

export interface PortfolioItem {
  id: string
  title: string
  category: Exclude<PortfolioCategory, 'all'>
  description: string
  imageUrl: string
  tags: string[]
  featured: boolean
  createdAt: string
}

export const portfolioCategoryLabels: Record<PortfolioCategory, string> = {
  'all': 'All Work',
  'manicures': 'Manicures',
  'pedicures': 'Pedicures',
  'nail-art': 'Nail Art',
  'special-occasions': 'Special Occasions',
  'seasonal-designs': 'Seasonal Designs',
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: '1',
    title: 'Rose Gold Elegance',
    category: 'manicures',
    description: 'Sophisticated rose gold chrome finish with delicate accent nails',
    imageUrl: '/images/portfolio/rose-gold-manicure.jpg',
    tags: ['chrome', 'rose gold', 'elegant'],
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Floral Spring Design',
    category: 'nail-art',
    description: 'Hand-painted cherry blossoms on nude base with 3D elements',
    imageUrl: '/images/portfolio/floral-spring.jpg',
    tags: ['floral', 'spring', '3d', 'hand-painted'],
    featured: true,
    createdAt: '2024-03-20',
  },
  {
    id: '3',
    title: 'Bridal White & Gold',
    category: 'special-occasions',
    description: 'Classic French with gold leaf accents perfect for wedding day',
    imageUrl: '/images/portfolio/bridal-white-gold.jpg',
    tags: ['bridal', 'wedding', 'gold', 'french'],
    featured: true,
    createdAt: '2024-02-14',
  },
  {
    id: '4',
    title: 'Luxe Spa Pedicure',
    category: 'pedicures',
    description: 'Coral gel polish with crystal embellishments on big toes',
    imageUrl: '/images/portfolio/luxe-spa-pedicure.jpg',
    tags: ['gel', 'coral', 'crystals', 'spa'],
    featured: false,
    createdAt: '2024-01-22',
  },
  {
    id: '5',
    title: 'Abstract Art Nails',
    category: 'nail-art',
    description: 'Modern abstract design in blush, lavender, and gold',
    imageUrl: '/images/portfolio/abstract-art.jpg',
    tags: ['abstract', 'modern', 'colorful'],
    featured: true,
    createdAt: '2024-03-05',
  },
  {
    id: '6',
    title: 'Halloween Gothic',
    category: 'seasonal-designs',
    description: 'Spooky spider web design with matte black and orange',
    imageUrl: '/images/portfolio/halloween-gothic.jpg',
    tags: ['halloween', 'gothic', 'seasonal', 'matte'],
    featured: false,
    createdAt: '2023-10-15',
  },
  {
    id: '7',
    title: 'Classic French Manicure',
    category: 'manicures',
    description: 'Timeless French tips with perfect precision and shine',
    imageUrl: '/images/portfolio/classic-french.jpg',
    tags: ['french', 'classic', 'elegant'],
    featured: false,
    createdAt: '2024-01-10',
  },
  {
    id: '8',
    title: 'Ombré Sunset',
    category: 'nail-art',
    description: 'Stunning gradient from coral to purple with glitter fade',
    imageUrl: '/images/portfolio/ombre-sunset.jpg',
    tags: ['ombré', 'gradient', 'glitter', 'sunset'],
    featured: true,
    createdAt: '2024-03-12',
  },
  {
    id: '9',
    title: 'Winter Wonderland',
    category: 'seasonal-designs',
    description: 'Icy blue with snowflake art and silver accents',
    imageUrl: '/images/portfolio/winter-wonderland.jpg',
    tags: ['winter', 'snowflake', 'blue', 'silver'],
    featured: false,
    createdAt: '2023-12-10',
  },
  {
    id: '10',
    title: 'Prom Night Glam',
    category: 'special-occasions',
    description: 'Sparkling nude base with rhinestone accents',
    imageUrl: '/images/portfolio/prom-glam.jpg',
    tags: ['prom', 'rhinestones', 'glam', 'sparkle'],
    featured: false,
    createdAt: '2024-04-20',
  },
  {
    id: '11',
    title: 'Tropical Vibes',
    category: 'pedicures',
    description: 'Bright turquoise with palm leaf designs',
    imageUrl: '/images/portfolio/tropical-pedicure.jpg',
    tags: ['tropical', 'summer', 'turquoise', 'palm'],
    featured: true,
    createdAt: '2024-05-15',
  },
  {
    id: '12',
    title: 'Marble Elegance',
    category: 'nail-art',
    description: 'White marble effect with gold veining',
    imageUrl: '/images/portfolio/marble-elegance.jpg',
    tags: ['marble', 'gold', 'elegant', 'luxe'],
    featured: true,
    createdAt: '2024-02-28',
  },
  {
    id: '13',
    title: 'Matte Black Chic',
    category: 'manicures',
    description: 'Sophisticated matte black with glossy accent nail',
    imageUrl: '/images/portfolio/matte-black.jpg',
    tags: ['matte', 'black', 'modern', 'chic'],
    featured: false,
    createdAt: '2024-03-18',
  },
  {
    id: '14',
    title: 'Cherry Blossom Art',
    category: 'nail-art',
    description: 'Delicate hand-painted cherry blossoms on soft pink',
    imageUrl: '/images/portfolio/cherry-blossom.jpg',
    tags: ['cherry blossom', 'floral', 'spring', 'pink'],
    featured: true,
    createdAt: '2024-03-25',
  },
  {
    id: '15',
    title: 'Valentine\'s Love',
    category: 'seasonal-designs',
    description: 'Romantic hearts and roses in red and pink',
    imageUrl: '/images/portfolio/valentines-love.jpg',
    tags: ['valentine', 'hearts', 'romantic', 'red'],
    featured: false,
    createdAt: '2024-02-10',
  },
  {
    id: '16',
    title: 'Nude Minimalist',
    category: 'manicures',
    description: 'Clean nude nails with single gold stripe accent',
    imageUrl: '/images/portfolio/nude-minimalist.jpg',
    tags: ['nude', 'minimalist', 'gold', 'simple'],
    featured: false,
    createdAt: '2024-01-30',
  },
  {
    id: '17',
    title: 'Glitter Gradient',
    category: 'nail-art',
    description: 'Champagne glitter fading from tips to base',
    imageUrl: '/images/portfolio/glitter-gradient.jpg',
    tags: ['glitter', 'gradient', 'champagne', 'sparkle'],
    featured: true,
    createdAt: '2024-04-05',
  },
  {
    id: '18',
    title: 'Summer Neon Pop',
    category: 'pedicures',
    description: 'Bold neon colors perfect for summer sandals',
    imageUrl: '/images/portfolio/neon-pedicure.jpg',
    tags: ['neon', 'summer', 'bright', 'bold'],
    featured: false,
    createdAt: '2024-06-01',
  },
  {
    id: '19',
    title: 'Autumn Leaves',
    category: 'seasonal-designs',
    description: 'Fall-inspired design with burnt orange and gold leaves',
    imageUrl: '/images/portfolio/autumn-leaves.jpg',
    tags: ['autumn', 'fall', 'leaves', 'orange'],
    featured: true,
    createdAt: '2023-09-22',
  },
  {
    id: '20',
    title: 'Birthday Celebration',
    category: 'special-occasions',
    description: 'Fun confetti design with rainbow sparkles',
    imageUrl: '/images/portfolio/birthday-confetti.jpg',
    tags: ['birthday', 'confetti', 'rainbow', 'celebration'],
    featured: false,
    createdAt: '2024-03-30',
  },
  {
    id: '21',
    title: 'Ocean Waves',
    category: 'nail-art',
    description: 'Realistic wave art in blue and turquoise tones',
    imageUrl: '/images/portfolio/ocean-waves.jpg',
    tags: ['ocean', 'waves', 'blue', 'realistic'],
    featured: true,
    createdAt: '2024-05-20',
  },
  {
    id: '22',
    title: 'Chrome Pink Mirror',
    category: 'manicures',
    description: 'High-shine pink chrome with mirror finish',
    imageUrl: '/images/portfolio/chrome-pink.jpg',
    tags: ['chrome', 'pink', 'mirror', 'shine'],
    featured: false,
    createdAt: '2024-04-15',
  },
  {
    id: '23',
    title: 'Butterfly Dreams',
    category: 'nail-art',
    description: '3D butterfly accents with holographic wings',
    imageUrl: '/images/portfolio/butterfly-dreams.jpg',
    tags: ['butterfly', '3d', 'holographic', 'whimsical'],
    featured: true,
    createdAt: '2024-05-10',
  },
  {
    id: '24',
    title: 'Christmas Sparkle',
    category: 'seasonal-designs',
    description: 'Red and green with snowflakes and gold glitter',
    imageUrl: '/images/portfolio/christmas-sparkle.jpg',
    tags: ['christmas', 'holiday', 'red', 'green'],
    featured: false,
    createdAt: '2023-12-15',
  },
  {
    id: '25',
    title: 'Lavender Fields',
    category: 'manicures',
    description: 'Soft lavender with white floral accents',
    imageUrl: '/images/portfolio/lavender-fields.jpg',
    tags: ['lavender', 'purple', 'floral', 'soft'],
    featured: false,
    createdAt: '2024-04-25',
  },
  {
    id: '26',
    title: 'Geometric Modern',
    category: 'nail-art',
    description: 'Bold geometric patterns in black and white',
    imageUrl: '/images/portfolio/geometric-modern.jpg',
    tags: ['geometric', 'modern', 'black', 'white'],
    featured: true,
    createdAt: '2024-05-05',
  },
  {
    id: '27',
    title: 'Anniversary Roses',
    category: 'special-occasions',
    description: 'Romantic red roses with gold leaf details',
    imageUrl: '/images/portfolio/anniversary-roses.jpg',
    tags: ['anniversary', 'roses', 'romantic', 'gold'],
    featured: false,
    createdAt: '2024-02-20',
  },
  {
    id: '28',
    title: 'Beach Sunset Toes',
    category: 'pedicures',
    description: 'Gradient sunset colors perfect for beach season',
    imageUrl: '/images/portfolio/beach-sunset-toes.jpg',
    tags: ['beach', 'sunset', 'gradient', 'summer'],
    featured: false,
    createdAt: '2024-06-10',
  },
  {
    id: '29',
    title: 'Galaxy Nails',
    category: 'nail-art',
    description: 'Stunning galaxy effect with stars and planets',
    imageUrl: '/images/portfolio/galaxy-nails.jpg',
    tags: ['galaxy', 'space', 'stars', 'cosmic'],
    featured: true,
    createdAt: '2024-05-28',
  },
  {
    id: '30',
    title: 'New Year Glam',
    category: 'seasonal-designs',
    description: 'Sparkly silver and gold for New Year celebrations',
    imageUrl: '/images/portfolio/new-year-glam.jpg',
    tags: ['new year', 'glam', 'silver', 'gold'],
    featured: false,
    createdAt: '2023-12-28',
  },
]